version: '3.8'

services:
  kali-mcp-commander:
    build:
      context: .
      dockerfile: Dockerfile.full
    container_name: kali-mcp-commander-full
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/app/config
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Add more resources if needed for full Kali tools
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G

  desktop-commander:
    image: node:18-alpine
    container_name: desktop-commander-mcp-full
    command: npx @wonderwhy-er/desktop-commander@latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      kali-mcp-commander:
        condition: service_started
    environment:
      - MCP_SERVER_URL=http://localhost:8080
    network_mode: host

